# Generated by Django 5.1.2 on 2024-10-11 14:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0002_initial"),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name="ticket",
            unique_together=set(),
        ),
        migrations.AlterField(
            model_name="play",
            name="description",
            field=models.TextField(blank=True),
        ),
        migrations.AddConstraint(
            model_name="ticket",
            constraint=models.UniqueConstraint(
                fields=("row", "seat", "performance"), name="unique_ticket"
            ),
        ),
    ]
