# Generated by Django 5.1.2 on 2024-10-12 10:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        (
            "theatre",
            "0003_alter_ticket_unique_together_alter_play_description_and_more",
        ),
    ]

    operations = [
        migrations.AlterField(
            model_name="play",
            name="actors",
            field=models.ManyToManyField(related_name="plays", to="theatre.actor"),
        ),
        migrations.AlterField(
            model_name="play",
            name="genres",
            field=models.ManyToManyField(related_name="plays", to="theatre.genre"),
        ),
    ]
