# Generated by Django 5.1.2 on 2024-10-13 09:40

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0004_alter_play_actors_alter_play_genres"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="reservation",
            field=models.ForeignKey(
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                to="theatre.reservation",
            ),
        ),
    ]
