# Generated by Django 5.1.2 on 2024-10-13 09:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0006_reservation_ticket_alter_ticket_reservation"),
    ]

    operations = [
        migrations.AlterField(
            model_name="ticket",
            name="reservation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="ticket_reservation",
                to="theatre.reservation",
            ),
        ),
    ]
