# Generated by Django 5.1.2 on 2024-10-13 12:04

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("theatre", "0008_alter_reservation_ticket_alter_ticket_reservation"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="reservation",
            name="ticket",
        ),
    ]
